version: '3.1'
services:

  chiccrm:
    # Specify either an image or a build context
    image: chiccrm-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3434:3434
    # depends_on:
    #   - backendchic

volumes:
  db_data2:
