
import { Montserrat } from "next/font/google";
import "./globals.css";
import { StateProvider } from '@/context/Context'

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
          <header></header>
          <StateProvider>
            {children}
          </StateProvider>          
          <footer></footer>
      </body>
    </html>
  );
}
