
import "./globals.css";
import { StateProvider } from '@/context/Context'
import ThemeRegistry from "@/utils/ThemeRegistry";
import { SpeedInsights } from '@vercel/speed-insights/next';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeRegistry options={{ key: 'mui-theme' }}>
      <body>
          <header></header>
          <StateProvider>
            {children}
            <SpeedInsights/>
          </StateProvider>          
          <footer></footer>
      </body>
      </ThemeRegistry>
    </html>
  );
}
