import React from 'react'
import "./globals.css";
import { StateProvider } from '@/context/Context'
import ThemeRegistry from "@/utils/ThemeRegistry";
import { SpeedInsights } from '@vercel/speed-insights/next';
import ComingSoon from '@/components/comingSoon/page';

export const metadata = {
    title: "ChicCRM",
    description: "Generated by create next app",
};

export default function RootLayout({ children, isComingSoon }) {
    return (
        <html lang="en">
            <ThemeRegistry options={{ key: 'mui-theme' }}>
                {/* <body className={isComingSoon ? 'coming-soon' : ''}>
          <header></header>
          <StateProvider>
            {children}
            <SpeedInsights />
          </StateProvider>
          <footer></footer>
        </body> */}
                <body>
                    <div className='sm:block lg:hidden m-0 p-0'>
                        <ComingSoon />
                    </div>
                    <div className='sm:hidden lg:block m-0 p-0'>
                        <header></header>
                        <StateProvider>
                            {children}
                            <SpeedInsights />
                        </StateProvider>
                        <footer></footer>
                    </div>
                </body>
            </ThemeRegistry>
        </html>
    );
}