'use client'
import React, { useContext } from 'react'
import VerificationCodeInput from '../../app/ui/login/OTPverify/VerificationCodeotp'
import { Box, Button } from '@mui/material';
import handleotp from "@/handle/otpvelify"
import handleqrcode from "@/handle/autenvelify"
import { StateContext } from '@/context/Context';
import Loading from '@/components/loading/index'
import CustomBackground from '@/components/Background/page'

function Authenverify() {

  const HandleOTP = handleotp();
  const HandleQRCode = handleqrcode();
  const { state } = useContext(StateContext);

  return (
    <CustomBackground>
      <Box>
        <Box sx={{ textAlign: 'left', color: '#1F2939', fontSize: 20, fontWeight: '700' }}>Enter Code from Authenticator </Box>
        <Box sx={{ textAlign: 'left', color: '#778296', fontSize: 15, mt: '8px' }}>Enter code generated by your Authenticator app to enable two-factor authentication.</Box>
      </Box>
      <Box>
        <Box sx={{ mb: '10px', color:'#778296', fontSize:'14px', fontWeight:'500' }}>Code</Box>
        <VerificationCodeInput onChange={HandleOTP.handleCodeChange} />
      </Box>
      <Box sx={{ display: 'flex', justifyContent: 'center' }}>
        <Button variant="contained" onClick={HandleQRCode.verifyauthen} sx={{ transition: 'transform 0.3s ease', '&:hover': { transform: 'scale(1.03)', }, }} style={{ background: state.loading ? '#e5e5e5' : '#84BAA1', width: '100%', height: '44px', textTransform: 'capitalize', marginTop: 10, boxShadow: '0px 0px 0px', borderRadius: '8px', fontWeight: '600', cursor: state.loading ? 'not-allowed' : 'pointer', }} disabled={state.loading}>{state.loading ? (<Loading />) : "Next"}</Button>
      </Box>
    </CustomBackground>
  )
}
export default Authenverify